### ISSUE TITLE
 Fig had an Error!: Failed to init logger

### ISSUE THREAD

**Issue by Mellbourn** [withfig/fig#1192]
### Description:

Fig stopped working. When I create a new pane in tmux, I immediately get this error message

```
Fig had an Error!: Failed to init logger

Caused by:
    0: failed to create log file
    1: Permission denied (os error 13)
```

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.3.0|Version 1.0.56 (B416)|/opt/homebrew/bin/zsh|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.56 (B416) [Swedish] 
UserShell: /opt/homebrew/bin/zsh
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/klas.mellbourn/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: false
PseudoTerminal Path: /Users/klas.mellbourn/code/klarna/klarna-app/master/bin:/Users/klas.mellbourn/.asdf/installs/python/3.9.10/bin:/Users/klas.mellbourn/.asdf/installs/python/2.7.18/bin:/bin:/Users/klas.mellbourn/.asdf/installs/ruby/3.1.0/bin:/Users/klas.mellbourn/.asdf/installs/bundler/2.3.3/exe:/Users/klas.mellbourn/.asdf/installs/direnv/2.30.3/bin:/Users/klas.mellbourn/.zinit/plugins/paulirish---git-open:/Users/klas.mellbourn/.zinit/plugins/morgant---tools-osx/src:/Users/klas.mellbourn/.asdf/shims:/Users/klas.mellbourn/.asdf/bin:/Users/klas.mellbourn/.zinit/polaris/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/sqlite/bin:/Applications/Android Studio.app/Contents/jre/Contents/Home/bin:/Users/klas.mellbourn/.volta/bin:/Users/klas.mellbourn/bin:/Users/klas.mellbourn/.cargo/bin:/Users/klas.mellbourn/.local/bin:/Users/klas.mellbourn/.manually-installed/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/homebrew/bin:/Users/klas.mellbourn/.local/bin:/Users/klas.mellbourn/.fig/bin:/Users/klas.mellbourn/.local/bin:/opt/homebrew/sbin:/opt/homebrew/opt/awscli@1/bin:/Users/klas.mellbourn/Library/Android/sdk/tools/bin:/Users/klas.mellbourn/Library/Android/sdk/platform-tools:/opt/homebrew/opt/fzf/bin:/Users/klas.mellbourn/.zinit/plugins/unixorn---git-extra-commands/bin
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current terminal session: ???
Current working directory: ???
Current window identifier: ???</pre>
</p>
</details>

**Comment by SeparateRecords** [comment]
cc @grant0417

**Comment by grant0417** [comment]
It looks like there are some permission issues with your `.fig` folder.

Try running `sudo chown -R user ~/.fig` where the user is your username.

**Comment by SeparateRecords** [comment]
Should be fixed if you run this command 🙂

**Comment by nick-youngblut** [comment]
`sudo chown -R $USER ~/.fig` didn't help. My specific error:

```
Fig failed to init logger (d8ac4f01-697d-412d-8a33-014cf35352fa): Failed to init logger

Caused by:
    Permission denied (os error 13)
```

All files in my `~/.fig/` directory are owned by me and have read/write permissions. I'm using `fig_cli 2.13.1` on Ubuntu 22.04

**Comment by nick-youngblut** [comment]
Any ideas on where the permissions issue might be coming from? I just need to know where to look in order to try and troubleshoot this issue myself.

**Comment by grant0417** [comment]
Hey @nick-youngblut, sorry I didn't see this before, I've seen this come up a couple times but have never been able to figure out what it is.

There is a setting however to suppress the error and just continue without logging:

```bash
fig _ local-state figterm.suppress_log_error true
```

**Comment by nick-youngblut** [comment]
Thanks @grant0417 ! 

`fig _ local-state figterm.suppress_log_error true` did stop the error:

```
Fig failed to init logger (d8ac4f01-697d-412d-8a33-014cf35352fa): Failed to init logger

Caused by:
    Permission denied (os error 13)
```

...but I still get the following error when running `fig source`:

```
error: Permission denied (os error 13)
```

**Comment by grant0417** [comment]
Hmm, that makes me think it is a real permissions issue! Can you check the permissions of `/var/tmp/fig/$USER` and `~/Library/Application Support/fig/`

**Comment by nick-youngblut** [comment]
Permissions at `/var/tmp/fig/$USER` don't seem to be the problem. `~/Library/Application Support/fig/` doesn't exist, probably since I'm using ubuntu (22.04).

Of note: I currently use multiple Ubuntu 22.04 VMs, which were all created at about the same time and all use bash 5.1.15(1)-release. I'm only running into this permissions issue with fig on one of the VMs, and I cannot determine why. As far as I can tell, all of the VMs are basically the same. The problematic VM was created a few weeks after the other VMs, but it appears to be the same.

**Comment by nick-youngblut** [comment]
`~/.config/fig` does not exist. I have the appropriate permissions for `/var/tmp/fig/$USER`

**Comment by grant0417** [comment]
Can you try making `~/.config/fig`?

**Comment by nick-youngblut** [comment]
Creating `~/.config/fig` does not help. I should note that `~/.config/fig` does not exist in the VMs where `fig` is working for me.
