### ISSUE TITLE
Autocomplete not showing up in VsCode terminal.

### ISSUE THREAD

**Issue by NedAckland** [withfig/fig#1368]
### Sanity checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have typed 'git ' and included a screenshot of the Debugger (click the Fig icon in the macOS menu bar)

### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

It was working originally but left, I restarted my laptop and it came back but around a week later the same thing happened again. Works fine in iTerm.

Restarting has not worked this time and now it no longer shows up in iTerm.

Tried creating a new terminal.
Fig doctor shows nothing wrong
Have tried running fig source. - No such file or directory (os error 2)

<img width="442" alt="Screenshot 2022-04-25 at 10 27 18" src="https://user-images.githubusercontent.com/48385424/165061319-c44bfb22-a363-4807-9bda-0d3d7f7066cd.png">

### Environment

```bash
# Fig Diagnostics
## Fig details:
  - Fig version: Version 1.0.57 (B439) [British]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path: 
  - Installation Script: true
  - PseudoTerminal Path: /opt/homebrew/bin:/opt/homebrew/sbin:/Users/dojo/.nvm/versions/node/v14.17.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/dojo/opt/anaconda3/bin:/Users/dojo/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/dojo/.nvm/versions/node/v14.17.1/bin:/Users/dojo/.fig/bin:/Users/dojo/.local/bin
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro17,1
  - Chip: Apple M1
  - Cores: 8 (4 performance and 4 efficiency)
  - Memory: 16 GB
## OS Info:
  - macOS 12.1.0 (21C52)
## Environment:
  - User Shell: /bin/bash
  - Current Directory: /Users/dojo
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 60994/% (com.microsoft.VSCode)
  - Active Process: ??? (???) - ???
  - Installed via Brew: true
  - Environment Variables:
    - TERM=xterm-256color
    - TERM_SESSION_ID=DACBF934-4B82-4BE9-AE7D-0B44BA1BAEF7
    - PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/Users/dojo/.nvm/versions/node/v14.17.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/dojo/opt/anaconda3/bin:/Users/dojo/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/dojo/.nvm/versions/node/v14.17.1/bin:/Users/dojo/.fig/bin:/Users/dojo/.local/bin
    - FIG_INTEGRATION_VERSION=8
    - FIG_TERM_VERSION=4.3.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
```

**Comment by grant0417** [comment]
Hey @NedAckland, this should be fixed on stable, run `fig update` to get the latest version.

**Comment by nazarEnzo** [comment]
Have same issue after [vscode update](https://code.visualstudio.com/updates/v1_72)

**Comment by elgrantut** [comment]
Same over here. After updating vscode it began to fail.

**Comment by jiywww** [comment]
Same here, Fig does not work in the the internal terminal of VSCode

**Comment by icastillejogomez** [comment]
Same here! Macbook Pro with M1 Pro Apple chip. Fig works in iTerm2 but doesn't in VSCode integrated terminal

**Comment by Archetipo95** [comment]
Same Here macbook pro M1 fig not working even with accessibility off

**Comment by ArkoMO93** [comment]
Same here. I have a macbook air m1 and it doesn't work in the vscode integrated terminal

**Comment by ulfbrehmer** [comment]
Same here. M1 Macbook Pro. Broke today on 2 nov 2022. I have VScode version:

Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.5.0
Sandboxed: No

VSCode Fig extension is 0.0.6

And fig diagnostic says:
fig-details:
  - desktop-version: Version 1.0.62 (B542) [Swedish]
hardware-info:
  - model: MacBook Pro
  - model-id: MacBookPro18,3
  - chip-id: 
  - cores: 8
  - mem: 32 GB
os-info:
  - macOS 12.4.0 (21F79)
environment:
  - shell: /bin/bash
  - terminal: vscode
  - cwd: /Users/me/gitrepos/WebFrontend
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - FIG_PID: 3202
    - TERM: xterm-256color
    - SHELL: /bin/bash
    - TERM_SESSION_ID: 0771ae83-1aaa-42cf-965a-613c892daf3c
    - PATH: /Users/me/.nvm/versions/node/v18.11.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/me/.rbenv/shims:/Users/me/.fig/bin:/Users/me/.local/bin
    - FIG_WORKFLOWS_KEYBIND: ^f
    - FIG_INTEGRATION_VERSION: 8
    - FIG_TERM_VERSION: 2.5.3
    - FIG_TERM: 1
- integrations:
  - SSH: false
  - TMUX: false
  - iTerm: AutoLaunch script does not exist at /Users/me/Library/Application Support/iTerm2/Scripts/AutoLaunch/fig-iterm-integration.scpt.
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false

**Comment by ulfbrehmer** [comment]
OK, so I did run that command, the installation process ran. I got an error immediately after the installation progress bar completed: "Something went wrong :(
Error: Unexpected Server Error: P2024. Sentry ID: c4f35877185840639c46fb87c7165c4d.".The dashboard showed, saying fig did not install correctly. I ran fig doctor in a VSCode terminal and finally fig seems to work (it autocompletes at least).

**Comment by Deepak22448** [comment]
Open fig then navigate to "General" then set "Preferred Terminal" to "VSCode".
This worked me.

**Comment by rostik32** [comment]
> Open fig then navigate to "General" then set "Preferred Terminal" to "VSCode". This worked me.

Thanks! It's work

**Comment by jkworth** [comment]
For me it seems that if i am running VSCode in full screen mode. It appears to not be working. It works just fine if not in full screen mode. Seems there is an issue as to where the popup is rendering. If I swipe back to desktop I see it there.

**Comment by yaasin-raki2** [comment]
same here 😕

**Comment by jkworth** [comment]
After the latest update of the Mac OS 13.0.1, everything is working fine now. IDK if there was also an update to fig but no issues now.

**Comment by mschrage** [comment]
@ulfbrehmer @yaasin-raki2 this was resolved in #1964.

**Comment by ravisojitra** [comment]
I am using "[Cursor](https://www.cursor.so/)" IDE built on top of vscode. Fig's suggestion box works in VsCode but it doesn't work in Cursor.

I tried below:
Open fig then navigate to "General" then set "Preferred Terminal" to "VSCode".

But it still doesn't work.

**Comment by mxncson** [comment]
Up for `cursor` portability, i would like to transition to this IDE but i can't do i until fig works on there.
@ravisojitra Did you found any way to make it work on cursor ?
