### ISSUE TITLE
Pasting large commands of text into fig enabled fish terminal breaks CLI

### ISSUE THREAD

**Issue by rcousens** [withfig/fig#1673]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)

When pasting large amounts of text into a fish terminal window, the CLI input bugs out and does not enable me to execute the command.
![Screen Shot 2022-08-09 at 11 33 19 am](https://user-images.githubusercontent.com/6834920/183543544-7de41272-7042-4f02-aa17-01f19dee6e8d.png)

I have not found any way to recover the terminal session, so generally I just kill it if this happens.

If I disable the fig init scripts in ~/.config/fish/conf.d/00_fig_pre.fish and 99_fig_post.fish I can paste long commands fine:

![Screen Shot 2022-08-09 at 11 35 28 am](https://user-images.githubusercontent.com/6834920/183543773-7f433007-bedc-4692-bd0e-fd7240b68ee8.png)

### Details:
|macOS|Fig|Shell|
|-|-|-|
|12.4.0|Version 1.0.59 (B493)|/opt/homebrew/bin/fish|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.59 (B493) [Beta] [Australian] 
UserShell: /opt/homebrew/bin/fish
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/ross/.fig/bin/fig
Accessibility: true
SSH Integration: false
Tmux Integration: false
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
UNIX Socket Exists: true
Installation Script: true
PseudoTerminal Path: /Users/ross/.asdf/installs/python/3.10.4/bin:/Users/ross/.asdf/installs/direnv/2.31.0/bin:/Users/ross/.asdf/installs/packer/1.8.0/bin:/Users/ross/.asdf/installs/nomad/1.2.6/bin:/Users/ross/.asdf/installs/vault/1.10.0 ent/bin:/Users/ross/.asdf/installs/java/corretto-17.0.3.6.1/bin:/Users/ross/.asdf/installs/deno/1.23.1/bin:/Users/ross/.asdf/installs/deno/1.23.1/.deno/bin:/Users/ross/.asdf/installs/tflint/0.38.1/bin:/Users/ross/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ross/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/ross/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: fish (60245) - /dev/ttys004
Current terminal session: w1t0p0:18C0714D-5B7F-4046-B15A-D8EE1BC1AF8E
Current working directory: /Users/ross
Current window identifier: 10751/% (com.googlecode.iterm2)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @rcousens! What version of fish are you using? (Run `fish --version`)

**Comment by grant0417** [comment]
Hwy @rcousens, seems like this might have been a bug on the beta, can you try updating and see if you still have the issue.

**Comment by rcousens** [comment]
@grant0417 Thanks, I'll test now!

**Comment by rcousens** [comment]
```
## Fig details:
  - Fig version: Version 1.0.60 (B501) [Beta] [Australian]
  - Bundle path: /Applications/Fig.app
  - Autocomplete: true
  - Settings.json: true
  - Accessibility: true
  - Number of specs: 0
  - Symlinked dotfiles: false
  - Only insert on tab: false
  - Keybindings path:
  - Installation Script: true
  - PseudoTerminal Path: /Users/ross/.asdf/installs/python/3.10.4/bin:/Users/ross/.asdf/installs/direnv/2.31.0/bin:/Users/ross/.asdf/installs/packer/1.8.0/bin:/Users/ross/.asdf/installs/nomad/1.2.6/bin:/Users/ross/.asdf/installs/vault/1.10.0+ent/bin:/Users/ross/.asdf/installs/java/corretto-17.0.3.6.1/bin:/Users/ross/.asdf/installs/deno/1.23.1/bin:/Users/ross/.asdf/installs/deno/1.23.1/.deno/bin:/Users/ross/.asdf/installs/tflint/0.38.1/bin:/Users/ross/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ross/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/ross/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
  - SecureKeyboardInput: false
  - SecureKeyboardProcess: <none>
## Hardware Info:
  - Model Name: MacBook Pro
  - Model Identifier: MacBookPro18,1
  - Chip: Apple M1 Pro
  - Cores: 10 (8 performance and 2 efficiency)
  - Memory: 32 GB
## OS Info:
  - macOS 12.4.0 (21F79)
## Environment:
  - User Shell: /opt/homebrew/bin/fish
  - Current Directory: /Users/ross
  - CLI Installed: true
  - Executable Location: /opt/homebrew/bin/fig
  - Current Window ID: 16394/% (com.googlecode.iterm2)
  - Active Process: fish (24894) - /dev/ttys002
  - Terminal: iterm
  - Installed via Brew: true
  - Environment Variables:
    - TERM_SESSION_ID=w0t0p0:1F13316C-EB02-4B84-BDAF-51BE9650F2CF
    - TERM=xterm-256color
    - FIG_INTEGRATION_VERSION=8
    - PATH=/Users/ross/.asdf/installs/python/3.10.4/bin:/Users/ross/.asdf/installs/direnv/2.31.0/bin:/Users/ross/.asdf/installs/packer/1.8.0/bin:/Users/ross/.asdf/installs/nomad/1.2.6/bin:/Users/ross/.asdf/installs/vault/1.10.0+ent/bin:/Users/ross/.asdf/installs/java/corretto-17.0.3.6.1/bin:/Users/ross/.asdf/installs/deno/1.23.1/bin:/Users/ross/.asdf/installs/deno/1.23.1/.deno/bin:/Users/ross/.asdf/installs/tflint/0.38.1/bin:/Users/ross/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/ross/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/ross/.fig/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
    - FIG_PID=24894
    - FIG_TERM_VERSION=5.1.0
    - FIG_TERM=1
## Integrations:
  - SSH: false
  - TMUX: false
  - iTerm: installed!
  - Hyper: application is not present.
  - Visual Studio Code: installed!
  - Docker: false
  ```

![image](https://user-images.githubusercontent.com/6834920/184256891-b2fb1174-c1dd-4650-95db-3494e7f0aa77.png)  

```
❯ fish --version
fish, version 3.5.1
```
no dice :(

**Comment by rcousens** [comment]
I'll try reproducing in a different shell, though I'm guessing it'll probably be a fish only thing! 👍

**Comment by grant0417** [comment]
How many are you pasting there? Also what fish plugins are you using?

**Comment by rcousens** [comment]
@grant0417 Hrmm I can reproduce in bash, the behaviour is a little different though! It just freezes the CLI and doesn't show the pasted output.

![Screen Shot 2022-08-12 at 9 18 27 am](https://user-images.githubusercontent.com/6834920/184258040-8bac686c-4e93-4dca-8918-d26b91527252.png)

1008 characters -> no problem.
1138 -> problem occurs.

**Comment by rcousens** [comment]
Suspiciously close to 1024, maybe a buffer somewhere? The magic number is 1011. 1010 works, 1011 doesn't.

**Comment by rcousens** [comment]
Fish plugins (though I don't think they are the culprit):
```
❯ fisher list
jorgebucaran/fisher
jethrokuan/z
franciscolourenco/done
wfxr/forgit
patrickf1/fzf.fish
jorgebucaran/autopair.fish
ilancosman/tide@v5
```
My initial testing involved disabling all plugins except for the fig pre/post.

**Comment by rcousens** [comment]
I have a clue for you, I think bracketed paste mode is related. I can replicate the behaviour in numerous applications when fig is enabled (vim, nano, micro).

It's eating the end of bracketed paste mode somehow?

**Comment by rcousens** [comment]
Additionally, I can recreate the issue in Alacritty and MacOS Terminal.app, but not WezTerm! Weird!

**Comment by rcousens** [comment]
![image](https://user-images.githubusercontent.com/6834920/185393183-42d0815d-d0a7-46fd-b28d-5c21d85e14dd.png)

I disabled ALL my plugins (mv ~/.config/fish ~/.config/fish.backup), quit iTerm, reinstalled Fig, opened iTerm and started a shell with fish, and then pasted more than 1012 characters to recreate the issue. So I'm confident it's not plugin related. It could be related to the version of fish (3.5.1), but I can confirm the problem happens with a clean install of Fish and Fig 1.0.60 (B508).

This should be easy to recreate and only happens when I'm in the binary "fish (figterm)" which gets launched by the 00_fig_pre.fish script.

**Comment by rcousens** [comment]
Also, I think I am on to something with bracketed paste. Because if I type a lot of a's instead of PASTE a lot of a's then the problem doesn't occur:
![Screen Shot 2022-08-18 at 10 28 12 pm](https://user-images.githubusercontent.com/6834920/185394722-db6c7a03-0e7e-45de-97d5-e7e38d301cac.png)

1402 a's and no problem.

**Comment by rcousens** [comment]
@mpas97 Thanks, that's a useful work around! I had to set it to 4 bytes to get it to work (took about 3s to paste ~1200 a's). However, I still hope there is a permanent fix here!

**Comment by grant0417** [comment]
I believe this should be fixed on beta, also setting the `Chunk Size` to any number <1000 might work, so that would speed up the pasting.

**Comment by rcousens** [comment]
@grant0417 I'll test beta now, thanks for working on this! I did try 256 and 16 chunk size (didn't change the delay between chunks) and both resulted in the bug.

**Comment by rcousens** [comment]
```
## Fig details:
  - Fig version: Version 1.0.60 (B509) [Beta] [Australian]
  ```
![Screen Shot 2022-08-23 at 9 14 38 am](https://user-images.githubusercontent.com/6834920/186035126-7a64c9cd-d9b0-49af-bc53-9fb51b8302d4.png)

Error still there generally, but 4b chunk size fixes the issue. Anything over 4b and I still have the issue. At least I have a workaround for pasting certs and AWS creds in to my terminal.

**Comment by grant0417** [comment]
Make sure to open a new terminal session after updating, will keep investigating this!

**Comment by rcousens** [comment]
Problem still there with new iTerm2 and new terminal session (quit iTerm2, reopen, CMD-N for new terminal). Thanks for your persistence @grant0417. I haven't disabled fig generally yet because I love it so much, but I have a second setup with WezTerm for stuff where I need to paste!

**Comment by rcousens** [comment]
I've now disabled fig permanently (by renaming the ~/.config/fish/conf.d/00_fish_pre.fish and 99_fish_post.fish scripts) until this is fixed as it has been making the terminal generally unusable for me. Otherwise, I love fig and appreciate all the hard work you guys are doing. Thank you!

**Comment by grant0417** [comment]
I spend a while working out what is actually going on here, I believe the actual fix should be on beta soon (within the next couple hours).

So sorry once again @rcousens for the issue and thank you so much for your debugging on it!

**Comment by grant0417** [comment]
I know this is the second time I have said this, but I very thoroughly tested this time (plus it was a very strange bug)

**Comment by ChowRex** [comment]
> I've now disabled fig permanently (by renaming the ~/.config/fish/conf.d/00_fish_pre.fish and 99_fish_post.fish scripts) until this is fixed as it has been making the terminal generally unusable for me. Otherwise, I love fig and appreciate all the hard work you guys are doing. Thank you!

You don't need to do that, just rename the middle layer binary is okay for me.

**Comment by rcousens** [comment]
Wow, it's fixed! THANK YOU @grant0417, I *really* appreciate your effort on resolving this. 👏 🙏 🥳  

@ChowRex if you can confirm your use case is fixed then I will close this issue.

**Comment by ChowRex** [comment]
> Wow, it's fixed! THANK YOU @grant0417, I _really_ appreciate your effort on resolving this. 👏 🙏 🥳
> 
> @ChowRex if you can confirm your use case is fixed then I will close this issue.

I have tested again, correct my answer: rename the `~/.fig/bin` directory is a work around to fix this bug in current release version.

**Comment by rcousens** [comment]
@grant0417 Hi, I'm very happy with the fix! Thanks again! 

I'm going to close this issue as @ChowRex hasn't indicated he's still having issues either :)
