### ISSUE TITLE
bug: fig does not work when terminal fullscreen on macos 13

### ISSUE THREAD

**Issue by GitBiao** [withfig/fig#1964]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

macos Ventura 13.0

### Expected behaviour

fig does not work when terminal fullscreen on macos 13

### Actual behaviour

when i update macos 13 and set terminal fullscreen ，the fig does not work 。

**Comment by GitBiao** [comment]
i was also restar the computer  and restar the fig application
and fig doctor :
✔ Everything looks good!

  Fig still not working? Run fig issue to let us know!
  Or, email us at hello@fig.io!

**Comment by GitBiao** [comment]
i found that fig is working。on the fullscreen，fig‘s autocomplete not show . but when i push enter。 the autocomplete words will on the treminal window

**Comment by SeparateRecords** [comment]
Hey @GitBiao! This is a known issue but we don't have a public tracking issue for it yet so will leave this open. Should be fixed in the next Rust beta: https://withfig.notion.site/Getting-Setup-with-our-new-Rust-based-Fig-app-e41115459178463c898f1281303d9f08

**Comment by Mocha--** [comment]
having the same issue on iterm2 on macos Ventura 13.0.

would deeply appreciate if this issue can be fixed very soon.

**Comment by SeparateRecords** [comment]
AFAIK this is being worked on right now :)

**Comment by mschrage** [comment]
This _should_ be resolved on the next stable build - coming out in an hour or so.

**Comment by usr42** [comment]
@mschrage Which version should be the fixed one? I just updated to 2.7.4 and the issue is still in. But I was on an even older version before, so probably 2.7.4 does no include the fix, yet.
When the fix is out, I can test it.

**Comment by wxh06** [comment]
I can confirm that both iTerm2 and VSCode have experienced the same issue with Fig `2.7.2` or `2.7.4-beta.0` installed and feature "input method" enabled on macOS 13.0.0 (22A380)

In fact, the autocomplete popup does appear on the desktop.

![Screenshot 2022-11-04 at 16.19.02.png](https://user-images.githubusercontent.com/29367025/199928209-0755b034-7628-413c-aeb7-981c0fe58cac.png)

![Screenshot 2022-11-04 at 16.19.36.png](https://user-images.githubusercontent.com/29367025/199928034-aaeab86e-df27-4715-95b9-4aa80e34acc3.png)

### Environment

```yaml
fig-details:
  - 2.7.4-beta.0
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 13.0.0 (22A380)
environment:
  - shell: /Applications/Fig.app/Contents/MacOS/fig_desktop
  - terminal: <unknown>
  - cwd: /
  - exe-path: /Applications/Fig.app/Contents/MacOS/fig-darwin-universal
  - install-method: unknown
  - env-vars:
    - PATH: /usr/bin:/bin:/usr/sbin:/sbin
    - SHELL: /opt/homebrew/bin/zsh
```

**Comment by usr42** [comment]
FYI Version 2.7.4 still has the issue for me.

**Comment by Mocha--** [comment]
still seeing the issue in v2.7.5

**Comment by drnserhio** [comment]
oh my god, i updated new version 2.7.5, and my products jetbrains not correct auto complite outside the window 😭

**Comment by zanza89** [comment]
Hi I have the same issue where autocomplete window doesnt appear in fullscreen mode.. tested in intelliJ, android studio and visual studio code -> all have issue

**Comment by yash-bhan** [comment]
Hi

Mac OS: Ventura 13.0
I also have the exact same issue where autocomplete window doesn't appear when terminal is in fullscreen mode, I'm using iTerm2 and intelliJ.

**Comment by kevinebaugh** [comment]
Fixed for me in 2.7.6-beta.2 👍

**Comment by mschrage** [comment]
Thanks for confirming @kevinebaugh.

This should be resolved (🤞) on the latest beta `2.7.6-beta.2`. If you want to try it out now, run `fig settings app.beta true`.

Sorry again for the inconvenience.

**Comment by Mocha--** [comment]
thanks guys. Working for me as well.

**Comment by usr42** [comment]
Version 2.7.6-beta.2 fixed it for me as well. Thanks for the quick fix 👍

**Comment by jesalrathooddd** [comment]
@mschrage Run the beta command and now it's working. Thank you.

**Comment by mvila** [comment]
I have the same issue with the last macOS update (v13.0.1).

**Comment by mschrage** [comment]
The fix for this is live in 2.7.6! To upgrade to the latest version, run `fig update`.

**Comment by stoopman** [comment]
This is not fixed, I still have this issue. I have PHPStorm with fig integration running fullscreen on an external monitor. When typing cmd in terminal, the autocomplete 'window' appears in my native macbook screen at the bottom. Not inside the terminal on my external screen.
