### ISSUE TITLE
bug: Ctrl+J binding overridden after update

### ISSUE THREAD

**Issue by jswent** [withfig/fig#1995]
### Checks

- [X] I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue
- [X] I have run `fig doctor` in the affected terminal session
- [X] I have run `fig restart` and replicated the issue again

### Operating system

MacOS

### Expected behaviour

Prior to updating, I would use Ctrl+J/K for navigating down/up similar to vim bindings.

### Actual behaviour

I updated fig yesterday and ever since this functionality has stopped working. Ctrl+K still works fine for navigating up, however it seems Ctrl+J is being overridden by some form of accept-line. I have completely unbound ^j from my shell and my terminal (iTerm), however this did not cause issues before. 

https://user-images.githubusercontent.com/94636565/200117924-20ef8019-ac05-497c-86c3-3df7f1fdfb36.mov

Above video is first me using ctrl+j, and as you can see it accepts the current suggestion (which it should not). The third line is me first using ctrl+n to navigate down, and then trying ctrl+j again which accepts the suggestion. Below are my bindings.

<img width="794" alt="Screen Shot 2022-11-05 at 11 33 28 AM" src="https://user-images.githubusercontent.com/94636565/200117956-c8add957-263e-44a0-8b49-07dc9d7807c0.png">

### Environment

```yaml
fig-details:
  - 2.7.5
hardware-info:
  - model:
  - model-id:
  - chip-id: Apple M1 Max
  - cores: 10
  - mem: 64.00 GB
os-info:
  - macOS 12.5.1 (21G83)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/jswent
  - exe-path: /usr/local/bin/fig
  - install-method: unknown
  - env-vars:
    - DISPLAY: /private/tmp/com.apple.launchd.WWqquKIpB9/org.xquartz:0
    - FIGTERM_SESSION_ID: 21ed46e6-05a4-48c5-a478-f86d125f5da6
    - FIG_HOSTNAME: James-MacBook-Pro
    - FIG_TERM: 2.7.5
    - PATH: /Users/jswent/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/jswent/.cargo/bin:/Users/jswent/.fig/bin:/Users/jswent/.local/bin:/Users/jswent/Library/Application Support/Coursier/bin:/snap/bin:/Users/jswent/.local/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - FIG_PID: 5761
    - FIG_SET_PARENT: 21ed46e6-05a4-48c5-a478-f86d125f5da6
    - FIG_ACTIVE: True
```

**Comment by SeparateRecords** [comment]
Hey @jswent! Sorry about this bug. This is a pure oversight on our part and should be fixed soon, although I don't know exactly when and for which terminals.

Short description of the problem: we switched our keybinding logic from happening at the Fig app layer to happening in the terminal itself using our shell wrapper called Figterm. This has _loads_ of advantages, primarily reliability and speed, but one **major** disadvantage: terminals see enter and control+j as the literally the same sequence of bytes. Same with tab and control+i, backspace and control+h.

This is fixed with [CSI u](http://www.leonerd.org.uk/hacks/fixterms/) which we _are_ implementing, but unfortunately we're at the mercy of terminal emulators for upstream support. iTerm2 (which it looks like you're using) supports this, so do Kitty and WezTerm (both are great!). Not sure about others.

Quick fix: you can bind to option+j/k, or use control+n/p to navigate.

```bash
fig settings autocomplete.keybindings.option+j navigateDown
fig settings autocomplete.keybindings.option+k navigateUp
```

**Comment by grant0417** [comment]
We are trying to have a fix for this out in tomorrows beta (2.7.6), will update then on how to enable/status of ctrl keybindings

**Comment by jswent** [comment]
> We are trying to have a fix for this out in tomorrows beta (2.7.6), will update then on how to enable/status of ctrl keybindings

I just updated to 2.7.6 and fig crashes my terminal when loaded. Tried on bash and zsh.

**Comment by jswent** [comment]
Just ran `update` again and I can successfully load fig now, however the binding is still not working. Is there any way I can roll back to a previous version?

**Comment by SeparateRecords** [comment]
It's not enabled by default at the moment - you'll need to run these commands to enable it.
```
fig settings figterm.csi-u.enabled true
fig settings sync
```
Would love to have your feedback on it 🙂

**Comment by jswent** [comment]
Ah, my apologies. Working perfectly now! Will this be enabled by default in the future?

**Comment by SeparateRecords** [comment]
Happy to hear it! And yes it'll be the default, still some minor kinks to work out first but we're making great progress :)

**Comment by arisacoba** [comment]
> Quick fix: you can bind to option+j/k, or use control+n/p to navigate.
> 
> ```shell
> fig settings autocomplete.keybindings.option+j navigateDown
> fig settings autocomplete.keybindings.option+k navigateUp
> ```

This solution worked for me! Hopefully, this fix will be part of the update soon 🙏

**Comment by jswent** [comment]
> > Quick fix: you can bind to option+j/k, or use control+n/p to navigate.
> > ```shell
> > fig settings autocomplete.keybindings.option+j navigateDown
> > fig settings autocomplete.keybindings.option+k navigateUp
> > ```
> 
> This solution worked for me! Hopefully, this fix will be part of the update soon 🙏

ctrl+j/k should be working now if you prefer that, just apply the settings above from @clo4.

**Comment by antony-frolov** [comment]
Hi! Is the issue resolved right now? I've just ran into the same problem, ctlr+j inserts the suggestion when bound to go to the next one.

**Comment by thanhanofhcmus** [comment]
> Hi! Is the issue resolved right now? I've just ran into the same problem, ctlr+j inserts the suggestion when bound to go to the next one

Hey there,

I'm having the same problem you are. I tried enabling CSI-u, but that didn't work.

**Comment by cruzluna** [comment]
`fig settings figterm.csi-u.enabled true
fig settings sync`

Ran the above statements and still doesn't work.
