### ISSUE TITLE
Tab setting doesn't seem to work

### ISSUE THREAD

**Issue by warpdesign** [withfig/fig#408]
### Description:
> Please include a detailed description of the issue (and an image or screen recording, if applicable)
- open the settings and check `Show on tab`
- type `git c` then press `tab`

### What should happen:
Fig autocomplete window should appear.

### What's happened instead:
Nothing happens. Same thing with `cd D`,... Instead, the default bash text-based autocomplete appears.
 
### Details:
|macOS|Fig|Shell|
|-|-|-|
|11.5.0|Version 1.0.47 (B257)|/bin/bash|
<details><summary><code>fig diagnostic</code></summary>
<p>
<pre>Version 1.0.47 (B257) [French] 
UserShell: /bin/bash
Bundle path: /Applications/Fig.app
Autocomplete: true
Settings.json: true
CLI installed: true
CLI tool path: /Users/nico/.fig/bin/fig
Accessibility: true
Number of specs: 188
SSH Integration: false
Tmux Integration: true
Keybindings path: /Users/nico/.fig/user/keybindings
iTerm Integration: true [Authenticated]
Hyper Integration: false
VSCode Integration: true
Docker Integration: false
Symlinked dotfiles: false
Only insert on tab: false
Installation Script: true
PseudoTerminal Path: /Users/nico/.nvm/versions/node/v14.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/nico/.fig/bin:/usr/local/Cellar/qt/5.15.2/bin/
SecureKeyboardInput: false
SecureKeyboardProcess: <none>
Current active process: ??? (???) - ???
Current working directory: ???
Current window identifier: 1479/% (com.microsoft.VSCode)</pre>
</p>
</details>

**Comment by mschrage** [comment]
Hey @warpdesign! Thanks for reporting this. 

Can you try running `fig settings app.beta true`? This will trigger an update that should fix the issue.

If not, let's set up some time to chat! cc @fwesss

**Comment by warpdesign** [comment]
It seems to work after setting app.beta indeed.

However I noticed that when typing a command, then pressing `tab`, if I don't select anything from fig, but press `escape` instead, fig suggestions will disappear (as expected), but then tab won't work. I have to press enter or delete the entire line for tab to work again.

**Comment by callummr** [comment]
To add to this, enabling the same setting also seems to steal _all_ tab input while a Fig-compatible app is focused. This breaks tab completion, tab navigation, even CMD + tab while VS Code is focused, for example.

**Comment by fwesss** [comment]
@callummr This should be fixed in 1.0.49. Can you run `fig update` and let me know if you're still running into this?

**Comment by callummr** [comment]
Yep, fixed here. Thanks!

**Comment by milanzmitrovic** [comment]
I have same issue, after pressing tab autocomplete options just shake. I can't use tab to select option.

I have newest version of Fig and beta is enabled.

**Comment by androchentw** [comment]
I was having the same issue (shake when tab pressed) until I set up the following:

1. Go to Settings > Autocomplete > Keybindings
2. Click "+" to add keybinding on "Insert common prefix or navigate"
3. press "tab" and save
4. voila 💯 

---
the default would be "Insert common prefix"
> Insert shared prefix of available suggestions. Shake if there's no common prefix.

**Comment by milanzmitrovic** [comment]
Hi @androchentw thanks for comment!

I already have tab there, but it still does not work.

I have no idea what is causing this issue...

<img width="837" alt="Screenshot 2022-09-09 at 22 55 50" src="https://user-images.githubusercontent.com/58112365/189443629-bb55b3f3-0eba-41b3-adad-75dc410164a6.png">

**Comment by mschrage** [comment]
Hey @milanzmitrovic can you open a separate issue for this. This sounds like a slightly different bug.

Run `fig issue` and then also run `fig settings all` and add that output to the issue body.

**Comment by milanzmitrovic** [comment]
Thanks @mschrage !

I just created issue https://github.com/withfig/fig/issues/1769 .
